### ISSUE TITLE
No LICENSE file

### ISSUE THREAD

**Issue by srijanshetty** [saksham0808/IITkNet#3]
Add a LICENSE file, MIT or Apache to allow contributors to submit PRs

**Comment by sakshamsharma** [comment]
MIT License added. Thanks :)

**Comment by srijanshetty** [comment]
@saksham0808 : Though I couldn't test it :monkey: (I don't use windows), the effort is commendable :smile:

**Comment by sakshamsharma** [comment]
@srijanshetty Neither do I, never since I got all my OpenCV libraries set up in Ubuntu.. That's the reason I haven't been updating this code. Anyway, I wanted to talk about development, whether there is anything I could do which could get me started. I am getting into development these days, having done algos initially. I know openCV, and prefer coding in C++. Already have some experience in the field, am working on a shuttlecock tracking/prediction/robot-control project at the moment, which is working great Would love to have another project. If you have anything in mind which could get me started, do let me know :)
